# proto-file: src/config/config.proto
# proto-message: Config
# info above is used by https://github.com/jvolkman/intellij-protobuf-editor#path-settings
#
# Riner config file in the google protobuf text format.
# this file can be used to tell Riner what algorithms to run on which devices
# (GPUs/CPUs) and which pools to connect to, as well as some other settings.
#
# the layout of riner config files is specified in 'config.proto'.
# when writing your own config, we recommend using textproto helpers like
# the intellij protobuf editor mentioned above. There is probably one for your
# favourite editor
#
# if fields from the 'config.proto' specification are not assigned here,
# the default values from Config::fillInDefaultValuesIfNeeded in
# src/config/Config.cpp are chosen.
#

global_settings {
  api_port: 4028
  opencl_kernel_dir: "kernel/dir/" #dir which contains the opencl kernel files (e.g. ethash.cl)
  start_profile_name: "my_profile" #when running Riner with this config file, the tasks of "my_profile" get launched
}

profile {
  name: "my_profile"
  # now specify tasks that will run in parallel as this profile is started

  # Task 1: run AlgoEthashCL on all devices
  task {
    run_on_all_remaining_devices: true
    #run this task on every gpu except gpu 1, which will run the task below

    run_algoimpl_with_name: "EthashCL"
    #run the OpenCL ethash AlgoImpl. run riner --list_algoimpls for a list of all available AlgoImpls

    use_device_profile_with_name: "my_default_gpu_profile" 
    #my_gpu_profile has specific settings for AlgoEthashCL for this gpu type.
  }

  # Task 1: run AlgoCuckatoo31 on GPU 1 (use --list_devices to find out about indices)
  task {
    device_index: 1
    #gpu 1 will not run the task above, but this one.

    run_algoimpl_with_name: "Cuckatoo31Cl"

    use_device_profile_with_name: "my_AMD_gpu_profile" 
    #my_gpu_profile has specified other settings for AlgoCuckatoo31Cl
  }
}

device_profile {
  name: "my_AMD_gpu_profile"
  #device profile, example name suggests they should be used for AMD gpus

  settings_for_algoimpl {
    key: "EthashCL"
    #these settings are applied if AlgoEthashCL is started with this gpu profile

    value {
      num_threads: 4
      work_size: 1024
    }
  }
}

device_profile {
  name: "my_default_gpu_profile"
  #generic device profile for no particular gpu

  settings_for_algoimpl { #key value pairs
    key: "Cuckatoo31"

    value: { #settings:
        work_size: 2048
    }
  }

  settings_for_algoimpl {
    key: "EthashCL"
    
    value: {
      num_threads: 4
      work_size: 1024
    }
  }
}

# pools are listed by priority. 
# e.g. if there are two ethash pools, the top most one will get used first, 
# if that pool is unresponsive, work will get taken from the next ethash pool instead.
# To prevent idle time in such a case, riner has connections to all pools, even unused ones.
# if an unresponsive pool reawakens, its work will get used again.

version: "0.1"

pool { #if this pool is active it will provide work to all running AlgoImpls that are of pow_type "ethash"
  pow_type: "ethash"
  protocol: "stratum2"
  host: "127.0.0.1"
  port: 2345
  username: "user"
  password: "password"
}

pool {
  pow_type: "cuckatoo31"
  protocol: "stratum"
  host: "127.0.0.1"
  port: 2346
  username: "user"
  password: "password"
}

pool { #2nd ethash pool as a backup if the first one is unresponsive
  pow_type: "ethash"
  protocol: "stratum2"
  host: "127.0.0.1"
  port: 2347
  username: "user"
  password: "password"
}